###Registro de usuario nuevo
POST http://localhost:1234/users/signup
Content-Type: application/json

{
  "email": "zahid233u12@gmail.com",
  "password": "1234",
  "username": "zahidujsanksajsadjsalkndsa2"
}

###Iniciar sesión 
POST http://localhost:1234/users/signin
Content-Type: application/json

{
  "email": "zahid2331@gmail.com",
  "password": "1234"
  
}